---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: public.ecr.aws/y1b0a4i8/vpc-lattice-examples:frontend
        imagePullPolicy: Always
        env:
          - name: LAMBDAURL
            value: "http://service3-00e1705d843acd696.7d67968.vpc-lattice-svcs.us-west-2.on.aws"
          - name: BACKENDURL
            value: "http://service2-019aa4ee617c3e5c0.7d67968.vpc-lattice-svcs.us-west-2.on.aws"
        ports:
          - containerPort: 8080
        resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: front-end
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
