AWSTemplateFormatVersion: "2010-09-09"

Description: "Amazon VPC Lattice resources"

Parameters:
  ServiceNetworkName:
    Type: String
    Description: Amazon VPC Service Network name.

Resources:
# ---------- SERVICE NETWORK (and Auth policy)
  ServiceNetwork:
    Type: AWS::VpcLattice::ServiceNetwork
    Properties:
      Name: !Ref ServiceNetworkName
      AuthType: AWS_IAM
  
  ServiceNetworkAuthPolicy:
    Type: AWS::VpcLattice::AuthPolicy
    Properties:
      ResourceIdentifier: !Ref ServiceNetwork
      Policy:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'

Outputs:
  ServiceNetworkID:
    Value: !Ref ServiceNetwork
    Description: Service Network ID.